### ISSUE TITLE
babel-runtime/core-js/promise NOT FOUND ERROR

### ISSUE THREAD

**Issue by yanni4night** [sebastian-software/postcss-smart-import#27]
I encounter an error which looks like `babel-runtime` is in _devDependencies_ but not `dependencies`:

```
{ Error: Cannot find module 'babel-runtime/core-js/promise'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (~/node_modules/postcss-smart-import/lib/index.js:6:32)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
...
```

**Comment by swernerx** [comment]
Thanks for the report. Never experienced this on my own. But your comment seems to be right - it should be in the deps.

Fixed in https://github.com/sebastian-software/postcss-smart-import/commit/b5628681f68d05430fbf1f1e022820a2d130a9ca
